# Generated by Django 3.2 on 2022-06-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='working_period',
            field=models.FloatField(null=True),
        ),
    ]
