# Generated by Django 3.2 on 2022-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_consultant_working_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='working_period',
            field=models.FloatField(default=0),
        ),
    ]
