# Generated by Django 3.2 on 2022-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220617_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingperiod',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workingperiod',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
